name: docker-pipeline-anuharshini
on: push
jobs:
  docker-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print your Register Number
        run: echo "Hello World - 22IT002"

        - name: Checkout
  uses: actions/checkout@v4

